// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Only load dotenv in development
if (process.env.NODE_ENV !== 'production') {
  import('dotenv/config')
}
import { defineConfig } from 'prisma/config'

// Validate DATABASE_URL in production
if (process.env.NODE_ENV === 'production' && !process.env.DATABASE_URL) {
  throw new Error(
    'DATABASE_URL environment variable is not set in production. Please configure it in Railway.',
  )
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url:
      process.env.DATABASE_URL ||
      'postgresql://placeholder:placeholder@localhost:5432/placeholder',
  },
})
